"""Added Unavailability table

Revision ID: 64885a5c0d98
Revises: 14e923f1e4b2
Create Date: 2024-11-29 10:31:38.897879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64885a5c0d98'
down_revision = '14e923f1e4b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unavailability')
    # ### end Alembic commands ###
