"""Added is_authenticated() to user

Revision ID: 6589cc220293
Revises: 1cd31c49fd78
Create Date: 2024-11-26 13:59:41.501092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6589cc220293'
down_revision = '1cd31c49fd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
