"""Store shifts

Revision ID: ceebac954c06
Revises: 815827b7d53c
Create Date: 2024-11-27 16:32:35.717407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceebac954c06'
down_revision = '815827b7d53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('workers_required', sa.Integer(), nullable=False),
    sa.Column('creating_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creating_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift')
    # ### end Alembic commands ###
